registry:
    restart: always
    image: registry:2
    ports:
        - 5000:5000
    environment:
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_PATH: /etc/docker/htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
        - /var/lib/docker/registry:/var/lib/registry/docker/registry
        - ./htpasswd:/etc/docker/htpasswd
